try{;(function(){var aC=window._vwo_code;if(aC){window._vwo_j_e=window._vwo_j_e||0;if(window._vwo_j_e==1){window._vwo_mt="dupCode";clearTimeout(window._vwo_settings_timer);if(window.VWO&&window.VWO._&&window.VWO._.bIE){window._vwo_code.finish()}return}if(window._vwo_j_e==-1){window._vwo_j_e=1}}window._vwo_mt="live";try{window._vwo_tm="";var getMode=function(e){var n;if(window.name.indexOf(e)>-1){n=window.name}else{n=window.location.search.match("_vwo_m=([^&]*)");n=n&&n[1]}return n&&JSON.parse(decodeURIComponent(n))};if(window.name.indexOf("_vis_heatmap")>-1||window.name.indexOf("_vis_editor")>-1||getMode("_vwo_cc")||window.name.indexOf("_vis_preview")>-1){window._vwo_mt=window.name}else if(window._vwo_tm.length){window._vwo_mt=window._vwo_tm}else if(location.href.indexOf("_vis_opt_preview_combination")!==-1&&location.href.indexOf("_vis_test_id")!==-1){window._vwo_mt="sharedPreview"}if(window._vwo_mt!=="live"){if(!getMode("_vwo_cc")){_vwo_code.load('https://dev.visualwebsiteoptimizer.com/j.php?mode=' + encodeURIComponent(window._vwo_mt) + '&a=274377&f=0&u=' + encodeURIComponent(window._vis_opt_url||document.URL));}else{(function(){window._vwo_code&&window._vwo_code.finish();_vwo_ccc={u:"/j.php?a=274377&u=https%3A%2F%2Fwww.paltalk.com%2F&r=0.9849557329359588"};var s=document.createElement("script");s.src="https://app.vwo.com/visitor-behavior-analysis/dist/codechecker/cc.min.js?r="+Math.random();document.head.appendChild(s)})()}}}catch(e){var b=new Image;b.src="https://dev.visualwebsiteoptimizer.com/e.gif?s=mode_det&e="+encodeURIComponent(e&&e.stack&&e.stack.substring(0,1e3));aC&&window._vwo_code.finish()}})();if(window._vwo_mt==='live'){;window.VWO = window.VWO || []; window.VWO.push(['modifyClickPauseTime', { time: 0 }]);_vwo_code.sT=_vwo_code.finished();(function(c,a,e,d,b,z){function f(a,b,d){e.cookie=a+"="+b+"; expires="+new Date(864e5*d+ +new Date).toGMTString()+"; domain="+c+"; path=/"}-1==e.cookie.indexOf("_vis_opt_out")&&-1==d.location.href.indexOf("vwo_opt_out=1")&&(a=e.cookie.replace(/(?:(?:^|.*;\s*)_vwo_uuid_v2\s*=\s*([^;]*).*$)|^.*$/,"$1")||a,a=a.split("|"),b=new Image,c=d.location.hostname.replace(/^www\./,"")||c,b.src="https://dev.visualwebsiteoptimizer.com/v.gif?cd="+(window._vis_opt_cookieDays||0)+"&a=274377&d="+encodeURIComponent(c)+"&u="+a[0]+"&h="+a[1]+"&t="+z+"&r="+Math.random(),d.vwo_iehack_queue=[b],f("_vwo_uuid_v2",a.join("|"),366))})("paltalk.com","DDDD5F3D200FAB06923BF050D805C0157|df68465dea2cf422032279219791cff3",document,window,0,_vwo_code.sT);var _vwo_acc_id=274377;
clearTimeout(_vwo_settings_timer);_vwo_exp_ids=[],_vwo_exp={};window.VWO=window.VWO||[];
window.VWO.data={"url":{},"ts":1658405870,"pc":{"t":0,"a":3.5},"rp":90,"gC":[{"t":1,"c":[198,205],"et":1,"id":1},{"t":1,"c":[226,164],"et":1,"id":2},{"t":1,"c":[240,245],"et":1,"id":3}],"noSS":false};window.VWO.featureInfo={};_vwo_exp_ids.push('49');_vwo_exp['49']={"version":2,"clickmap":0,"globalCode":{},"type":"ANALYZE_HEATMAP","status":"RUNNING","pc_traffic":100,"name":"Heatmap","manual":false,"main":true,"urlRegex":"^.*$","exclude_url":"","multiple_domains":0,"segment_code":"true","sections":{"1":{"path":"","variations":{"1":""}}},"combs":{"1":1},"comb_n":{"1":"website"},"goals":{"1":{"urlRegex":"^.*$","excludeUrl":"","type":"ENGAGEMENT"}}};window._vwo_pa=window._vwo_pa || {};_vwo_exp_ids.push('50');_vwo_exp['50']={"version":2,"clickmap":0,"globalCode":{},"type":"ANALYZE_RECORDING","status":"RUNNING","pc_traffic":100,"name":"Visitor Sessions Recorded","manual":false,"main":true,"aK":1,"bl":"","wl":"","urlRegex":"^.*$","exclude_url":"^.*firstmet.*$|^.*50more.*$|^.*camfrog.*$","multiple_domains":0,"segment_code":"true","sections":{"1":{"path":"","variations":{"1":""}}},"combs":{"1":1},"comb_n":{"1":"website"},"goals":{"1":{"urlRegex":"^.*$","excludeUrl":"","type":"ENGAGEMENT"}}};var vwoCode = window._vwo_code; if(vwoCode.filterConfig && vwoCode.filterConfig.filterTime==='balanced'){ vwoCode.removeLoaderAndOverlay && vwoCode.removeLoaderAndOverlay() };var _vwo_style=document.getElementById('_vis_opt_path_hides'),_vwo_css= window._vwo_el_style || '{opacity:0 !important;filter:alpha(opacity=0) !important;background:none !important;} :root {--vwo-el-opacity:0 !important;--vwo-el-filter:alpha(opacity=0) !important;--vwo-el-bg:none !important;}';
if(_vwo_style){_vwo_style.parentNode.removeChild(_vwo_style);}(function(){var VWOOmniTemp={};window.VWOOmni=window.VWOOmni||{};                    for (var key in VWOOmniTemp) {
                        window.VWOOmni[key] = VWOOmniTemp[key];
                    }
                ;})();    (function(){window.VWO=window.VWO||[];var pollInterval=100;
        var _vis_data={};
        var intervalObj={};
        var analyticsTimerObj={};
        var experimentListObj={};window.VWO.push(["onVariationApplied",function(data){if(!data){return}var expId=data[1],variationId=data[2];if(expId&&variationId&&["VISUAL_AB","VISUAL","SPLIT_URL"].indexOf(window._vwo_exp[expId].type)>-1){}}])})();
    window.VWO.data.vi = window.VWO.data.vi || {"os":"Linux","dt":"desktop","br":"Chrome","de":"Other"};

VWO.load_co=function(a){var b=document.createElement('script');b.src=a;b.crossOrigin='anonymous';b.fetchPriority='high';b.type='text/javascript';b.innerText;b.onerror=function(){_vwo_code.finish();};document.getElementsByTagName('head')[0].appendChild(b);}
var _vwo_cookieDomain = 'paltalk.com', _vwo_uuid = 'DDDD5F3D200FAB06923BF050D805C0157';window.VWO=window.VWO||[];VWO._=VWO._||{};var _vis_opt_file = _vwo_code.use_existing_jquery() ? '7.0/vanj-3a8c03cc83fd9c554b5af6e1cc1ffa80.js' : '7.0/va-3a8c03cc83fd9c554b5af6e1cc1ffa80.js',_vwo_library_timer = setTimeout(function () {var vwoCode = _vwo_code; vwoCode.removeLoaderAndOverlay && vwoCode.removeLoaderAndOverlay(); vwoCode.finish()},vwoCode.library_tolerance()),_vis_opt_lib = (typeof _vis_opt_lib=='undefined')?'https://dev.visualwebsiteoptimizer.com/'+_vis_opt_file:_vis_opt_lib;VWO.load_co(_vis_opt_lib);VWO.load_co(window.VWO.trackLibPath || 'https://dev.visualwebsiteoptimizer.com/7.0/track-3a8c03cc83fd9c554b5af6e1cc1ffa80.js');_vwo_opa_cb = 'c79ac17b8d06ea26835b878ae8fde2ae';VWO.load_co(window.VWO.opaLibPath || 'https://dev.visualwebsiteoptimizer.com/analysis/4.0/opa-c79ac17b8d06ea26835b878ae8fde2ae.js');_vwo_worker_cb='70faafffa0475802f5ee03ca5ff74179';window._vwo_pa = window._vwo_pa || {};window._vwo_pa.sId = 'E0D122605D3ADE6A';window.VWO.data.as = "r1.visualwebsiteoptimizer.com";;window.VWO=window.VWO||[];window.VWO._=window.VWO._||{};VWO._.ac=VWO._.ac||{};; 
window.VWO = window.VWO || [];
window.VWO.data = window.VWO.data || {};
VWO.data.content={"fns":{"list":{"args":{"1":{}},"vn":1}}};;window.VWO = window.VWO||[];window.VWO._=window.VWO._||{};VWO._.ac=VWO._.ac||{};VWO._.ac.dNdOfst=1000;}}catch(e){_vwo_code.finish(); _vwo_code.removeLoaderAndOverlay && _vwo_code.removeLoaderAndOverlay(); var b=new Image;b.src="https://dev.visualwebsiteoptimizer.com/e.gif?a=274377&s=j.php&e="+encodeURIComponent(e && e.message && e.message.substring(0,1000))+"&url"+encodeURIComponent(window.location.href)}